version: '3.3'
services:
    db:
        image: mysql:5.7
        volumes:
            - ./mysql-dump/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: j2ee_project_db
            MYSQL_USER: testuser
            MYSQL_PASSWORD: root
        restart: always
        ports:
            - 3307:3306
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        ports:
            - '8081:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
    web:
        container_name: tomcat_container
        build:
            context: ./
            dockerfile: DockerfileTomcat
        depends_on:
            - db
        restart: always
        volumes:
            - ./target/J2EE_Project-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/J2EE_Project-1.0-SNAPSHOT.war
        ports:
            - '8082:8080'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: testdb1
            MYSQL_USER: testuser
            MYSQL_PASSWORD: root